### ISSUE TITLE
PyCloudStack run failed with log "'VMGuest' object has no attribute 'tsx'"

### ISSUE THREAD

**Issue by qzheng527** [intel/tdx-tools#533]
Tried example [`Operate VM via Libvirt`](https://github.com/intel/tdx-tools/tree/tdx-1.5/utils/pycloudstack#example-1-operate-vm-via-libvirt) but failed with log below.
```
Traceback (most recent call last):
  File "./start_vm.py", line 14, in <module>
    inst = vm_factory.new_vm(VM_TYPE_TD, auto_start=True)
  File "/home/zhengqi/.local/lib/python3.6/site-packages/pycloudstack/vmguest.py", line 400, in new_vm
    diskfile_path=diskfile_path, cpu_ids=cpu_ids)
  File "/home/zhengqi/.local/lib/python3.6/site-packages/pycloudstack/vmguest.py", line 91, in __init__
    self.vmm = vmm_class(self)
  File "/home/zhengqi/.local/lib/python3.6/site-packages/pycloudstack/vmm.py", line 143, in __init__
    self._xml = self._prepare_domain_xml()
  File "/home/zhengqi/.local/lib/python3.6/site-packages/pycloudstack/vmm.py", line 175, in _prepare_domain_xml
    self.set_cpu_params_xml(xmlobj)
  File "/home/zhengqi/.local/lib/python3.6/site-packages/pycloudstack/vmm.py", line 222, in set_cpu_params_xml
    if self.vminst.tsx is False:
AttributeError: 'VMGuest' object has no attribute 'tsx'
```

I installed the pycloudstack by `pip3 install --user pycloudstack`.
BTW, install from source was failed, asking for 'setup.py'.
```
cd ~/pycloudstack
pip3 install --user --upgrade .
```

**Comment by ruomengh** [comment]
Thanks for raising the issue. The project is end of life. Please refer to Red Hat blog [Enabling hardware-backed confidential computing with a CentOS SIG](https://www.redhat.com/en/blog/enabling-hardware-backed-confidential-computing-centos-sig) or Ubuntu blog [Intel® TDX 1.0 technology preview available on Ubuntu 23.10](https://ubuntu.com/blog/intel-tdx-1-0-preview-on-ubuntu-23-10) or SUSE blog [Intel® TDX Support Coming to SUSE Linux Enterprise Server](https://www.suse.com/c/intel-tdx-support-coming-to-suse-linux-enterprise-server/) for more information of TDX Early Preview.
